### ISSUE TITLE
[Epic] Set up backbone android app to display data from bluetooth

### ISSUE THREAD

**Issue by prokarius** [prokarius/cerulean-alley#2]
- [ ] Create backbone android app
- [ ] Connect bluetooth device to the app
- [ ] Display data from bluetooth device on the landing page of the app
